name: File Content Changes

on: [push]

jobs:
  run-file-content-command:
    runs-on: ubuntu-latest    
    steps:       
      # - name: file Content Checkout
      #   uses: actions/checkout@${{ github.sha }}        
      #   run: |
      #     echo "ls -a"
      #     ls -a
      
      # - name: Replace Command      
      -  uses: actions/checkout@${{ github.sha }}        
      -  uses: microsoft/variable-substitution@v1 
         with:
          files: '${{HOME}}/myapp/appsettings.json'
         env:
          ConnectionStrings.Default: ${{ secrets.SOME_CONNECTION_STRING }}
        # App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}

