name: Matrix implementation
on: push

jobs:
  run-on-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node_Version: [6,8,10]
      fail-fast: true
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_Version}}
          
      -  name: Display Node Version 
         run: node -v
        