name: Shell Command

on: 
  # push:
  pull_request: 
      branches: [develop]
  push:
      branches: [feature/**---gem]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      
      - name: checkout the branch
        uses: actions/checkout@v1

      - name: dotnet & node Version
        run: |
          echo "dotnet Verion ---" 
          dotnet --info
          echo "Node Verion ---" 
          node -v
          echo $GITHUB_WORKSPACE
  
  run-shell1-command:
    runs-on: ubuntu-latest
    needs: [run-shell-command]
    steps:
      - name: echo a string
        run: echo "Hello World from 1"
        
      - name: dotnet & node Version
        run: |
          echo "dotnet Verion ---" 
          dotnet --info
          echo "Node Verion ---" 
          node -v
      - name: perform check for prefix
        if: ${{ startsWith(github.event.pull_request.title, 'AB#') != true }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('The pull request title must start with "AB#[ADO work item number] - ". Example: "AB#475575 - Making the blue key component generic" ')
